name: Continuous Deployment to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # We could cache dependencies but this app hardly ever gets updated anyway
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        
      - name: Build
        run: yarn run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build
